Repository equinor/komodo, pull requests merged in 2023-03, with the labels that each got.

#349 Recognize main
  komodo/lint.py
Labels: maintenance

#356 Add time profiling
  komodo/cli.py
Labels: enhancement

#344 Ignore invalid versions/specifiers in pypi checker
  komodo/check_up_to_date_pypi.py
Labels: bug
