Repository equinor/komodo, pull requests merged in 2023-10, with the labels that each got.

#408 Fix ReleaseDir class to load *yml files
  komodo/yaml_file_types.py
  tests/test_yaml_file_types.py
Labels: bug

#386 Group upgrades komodo check pypi
  komodo/check_up_to_date_pypi.py
  tests/test_up_to_date_pypi.py
Labels: enhancement

#411 Allow deleting symlinks as well, not only directories
  komodo/switch.py
Labels: bug

#412 Utilize pathlib in test_switch.py
  tests/test_switch.py
Labels: maintenance
